nginx_docker:
  image: registry.cn-hangzhou.aliyuncs.com/tongxinhua1990/nginx
  volumes:
    - /Users/tongxinhua/home/local/docker/nginx/conf/docker_conf:/etc/nginx/conf.d
    - /Users/tongxinhua/home/local/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    - /data/logs/nginx:/var/log/nginx
  ports:
    - "80:80"
    - "403:403"
    - "8080:8080"
  links:
    - php7yafswoole
    - mysql57
  volumes_from:
    - php7yafswoole
  expose:
    - 80
    - 403
    - 8080
  dns:
    - 223.5.5.5

php7yafswoole:
  image: registry.cn-hangzhou.aliyuncs.com/tongxinhua1990/php_swoole
  volumes:
    - /Users/tongxinhua/home/local/docker/php72-yaf-swoole-master/conf/php.ini:/usr/local/etc/php/php.ini
    - /Users/tongxinhua/home/local/docker/php72-yaf-swoole-master/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - /Users/tongxinhua/home/local/docker/php72-yaf-swoole-master/conf/yac.ini:/usr/local/etc/php/conf.d/yac.ini
    - /Library/WebServer/Documents:/opt/www
    - /data/logs:/data/logs
  ports:
    - "9000:9000"
    - "9502:9501"
  links:
    - mysql57
  expose:
    - 9000
    - 9501
  dns:
    - 10.70.1.38
    - 114.114.114.114
    - 223.5.5.5


mysql57:
  image: registry.cn-hangzhou.aliyuncs.com/tongxinhua1990/mysql5.7.21
  ports:
    - "3306:3306"
  expose:
    - 3306
  environment:
    - MYSQL_ROOT_PASSWORD=19900613tong
    - MYSQL_ALLOW_EMPTY_PASSWORD=root
    - MYSQL_RANDOM_ROOT_PASSWORD=root
#  privileged: true
#  volumes:
#    - /Applications/XAMPP/xamppfiles/var/mysql:/var/lib/mysql
  dns:
    - 127.0.0.1
    - 223.5.5.5
